### PR TITLE
Shift ops

### PR DESCRIPTION
**Pull request by VoR0220**
may actually want to rebase to my fixed type branch before adding this.

### CODE REVIEW

**Comment by axic** [comment]
@VoR0220 can you please rebase your changes against my branch? I've rebased mine to develop now, which has the realdatatype merged. That should remove the above 4401369 merge commit.

**Comment by axic** [comment]
Also can you please explain to me whether your patch only supports it for the fixed-type or integers too?

**Comment by VoR0220** [comment]
it should only support it for rational to rationals...We should create a test for whether or not it will work with fixed types and it should be set to fail...unless Christian thinks we might be able to manipulate the bits underneath (which I think might just get confusing...but who knows...he may go for it...probably not though).

**Comment by VoR0220** [comment]
dammit...I fucked up here.

**Comment by VoR0220** [comment]
I'll take care of this tomorrow.

**Comment by axic** [comment]
I don't think it makes sense to support it for the fixed type, hence my question.

**Comment by VoR0220** [comment]
Well when you think about it, a fixed type is just one giant integer, just with awareness of where its radix is by the type name.

**Comment by axic** [comment]
As discussed on the other PR, shifting mostly is understood on binary values.  You can of course shift a float in C (well, the binary representation of it), but that wouldn't result in what you expect.

**Comment by axic** [comment]
@VoR0220 can you add tests for the this patch is a separate PR?

**Pull request merged**
